install(TARGETS ${PROJECT_NAME}
  RUNTIME DESTINATION bin COMPONENT Runtime)

install(FILES ${CMAKE_BINARY_DIR}/imgui.ini DESTINATION bin COMPONENT Runtime)

install(TARGETS ${PROJECT_NAME}-test
  RUNTIME DESTINATION bin COMPONENT Tests)

if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
  if(WIN32 AND (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "MSVC"))
    install(FILES "$<TARGET_PDB_FILE:${PROJECT_NAME}>" DESTINATION bin COMPONENT Runtime)
    install(FILES "$<TARGET_PDB_FILE:${PROJECT_NAME}-test>" DESTINATION bin COMPONENT Tests)
  endif()
endif()